language: node_js
os: linux
# dist: trusty

addons:
  chrome: stable

node_js:
  - '8'

notifications:
  email:
    recipients:
      - sebastien.jourdain@kitware.com
      - aron.helser@kitware.com
    on_success: change
    on_failure: always

cache:
  directories:
    - node_modules
    - Documentation/build-tmp

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgif-dev

script:
  - npm install -g markdown-pdf
  - npm run build:release
  - npm run validate
  - npm run bundle
  - markdown-pdf -c ./Documentation/content/users_guide/ -f Legal -o ./Documentation/content/users_guide/VeraInViewer-UserGuide.pdf ./Documentation/content/users_guide/index.md
  - git config --global user.name "Travis CI"
  - git config --global user.email "aron.helser@kitware.com"
  - export GIT_PUBLISH_URL=https://${GH_TOKEN}@github.com/CASL/VeraInView.git
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run doc:publish; fi

after_success:
  - npm run semantic-release

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
